#pragma once

// First-pass OpenThread core config for the nRF54L15 Arduino integration.
//
// This header is intentionally narrow: it trims subsystems that are not part of
// the initial CPUAPP FTD attach/role bring-up while leaving the core Thread
// stack shape intact.

#define OPENTHREAD_CONFIG_PLATFORM_INFO "NRF54L15-Clean-CPUAPP"

// Use OpenThread's mbedTLS crypto backend for Thread/MeshCoP so DTLS, HKDF,
// HMAC, AES-CCM, and PBKDF2 all share the same audited implementation.
#define OPENTHREAD_CONFIG_CRYPTO_LIB OPENTHREAD_CONFIG_CRYPTO_LIB_MBEDTLS

// Keep staged OpenThread heap allocations on the Arduino/platform allocator.
// Pulling the internal OpenThread heap also pulls in Instance heap ownership and
// is not needed for the current single-instance staged core.
#define OPENTHREAD_CONFIG_HEAP_EXTERNAL_ENABLE 1

#define OPENTHREAD_CONFIG_UPTIME_ENABLE 1
#define OPENTHREAD_CONFIG_LOG_LEVEL OT_LOG_LEVEL_INFO

#define OPENTHREAD_CONFIG_TCP_ENABLE 0

// MeshCoP/DTLS commissioning can fragment into several back-to-back 6LoWPAN
// frames. The default OpenThread pool is tight for this staged Arduino PAL,
// which still has a polling radio backend rather than Zephyr's IRQ pipeline.
#define OPENTHREAD_CONFIG_NUM_MESSAGE_BUFFERS 96
#define OPENTHREAD_CONFIG_6LOWPAN_REASSEMBLY_TIMEOUT 4
#define OPENTHREAD_CONFIG_MAC_STAY_AWAKE_BETWEEN_FRAGMENTS 1

#define OPENTHREAD_CONFIG_BACKBONE_ROUTER_ENABLE 0

#define OPENTHREAD_CONFIG_BORDER_AGENT_ENABLE 0
#define OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE 0
#define OPENTHREAD_CONFIG_BORDER_ROUTING_ENABLE 0

#define OPENTHREAD_CONFIG_BLE_TCAT_ENABLE 0

#define OPENTHREAD_CONFIG_CHANNEL_MANAGER_ENABLE 0
#define OPENTHREAD_CONFIG_CHANNEL_MONITOR_ENABLE 0

// The current PAL does not provide hardware MAC security/frame-counter
// handling, so staged-core bring-up must keep these services in software.
#define OPENTHREAD_CONFIG_MAC_SOFTWARE_ACK_TIMEOUT_ENABLE 1
#define OPENTHREAD_CONFIG_MAC_SOFTWARE_RETRANSMIT_ENABLE 1
#define OPENTHREAD_CONFIG_MAC_SOFTWARE_CSMA_BACKOFF_ENABLE 1
#define OPENTHREAD_CONFIG_MAC_SOFTWARE_TX_SECURITY_ENABLE 1
#define OPENTHREAD_CONFIG_MAC_SOFTWARE_RX_ON_WHEN_IDLE_ENABLE 1
#define OPENTHREAD_CONFIG_MAC_DEFAULT_MAX_FRAME_RETRIES_INDIRECT 3
#define OPENTHREAD_CONFIG_DEFAULT_SED_DATAGRAM_COUNT 4

#ifndef NRF54L15_CLEAN_OPENTHREAD_MESHCOP_ENABLE
#define NRF54L15_CLEAN_OPENTHREAD_MESHCOP_ENABLE 0
#endif

#define OPENTHREAD_CONFIG_COMMISSIONER_ENABLE \
  NRF54L15_CLEAN_OPENTHREAD_MESHCOP_ENABLE
#define OPENTHREAD_CONFIG_JOINER_ENABLE \
  NRF54L15_CLEAN_OPENTHREAD_MESHCOP_ENABLE
#define OPENTHREAD_CONFIG_SECURE_TRANSPORT_ENABLE \
  NRF54L15_CLEAN_OPENTHREAD_MESHCOP_ENABLE
#define OPENTHREAD_CONFIG_SEEKER_ENABLE \
  NRF54L15_CLEAN_OPENTHREAD_MESHCOP_ENABLE

#ifndef NRF54L15_CLEAN_OPENTHREAD_DNS_SD_ENABLE
#if defined(NRF54L15_CLEAN_MATTER_CORE_ENABLE) && \
    (NRF54L15_CLEAN_MATTER_CORE_ENABLE != 0)
#define NRF54L15_CLEAN_OPENTHREAD_DNS_SD_ENABLE 1
#else
#define NRF54L15_CLEAN_OPENTHREAD_DNS_SD_ENABLE 0
#endif
#endif

#ifndef NRF54L15_CLEAN_OPENTHREAD_SRP_CLIENT_ENABLE
#define NRF54L15_CLEAN_OPENTHREAD_SRP_CLIENT_ENABLE \
  NRF54L15_CLEAN_OPENTHREAD_DNS_SD_ENABLE
#endif

#ifndef NRF54L15_CLEAN_OPENTHREAD_MDNS_ENABLE
#define NRF54L15_CLEAN_OPENTHREAD_MDNS_ENABLE 0
#endif

#ifndef NRF54L15_CLEAN_OPENTHREAD_DNSSD_SERVER_ENABLE
#define NRF54L15_CLEAN_OPENTHREAD_DNSSD_SERVER_ENABLE 0
#endif

#define OPENTHREAD_CONFIG_DHCP6_CLIENT_ENABLE 0
#define OPENTHREAD_CONFIG_DHCP6_SERVER_ENABLE 0
#define OPENTHREAD_CONFIG_DNS_CLIENT_ENABLE \
  NRF54L15_CLEAN_OPENTHREAD_DNS_SD_ENABLE
#define OPENTHREAD_CONFIG_DNSSD_SERVER_ENABLE \
  NRF54L15_CLEAN_OPENTHREAD_DNSSD_SERVER_ENABLE

#define OPENTHREAD_CONFIG_ANNOUNCE_SENDER_ENABLE 0
#define OPENTHREAD_CONFIG_CHILD_SUPERVISION_INTERVAL 0
#define OPENTHREAD_CONFIG_CHILD_SUPERVISION_CHECK_TIMEOUT 0
#define OPENTHREAD_CONFIG_CHILD_SUPERVISION_OLDER_VERSION_CHILD_DEFAULT_INTERVAL 0
#define OPENTHREAD_CONFIG_DATASET_UPDATER_ENABLE 0
#define OPENTHREAD_CONFIG_HISTORY_TRACKER_ENABLE 0
#define OPENTHREAD_CONFIG_JAM_DETECTION_ENABLE 0
#define OPENTHREAD_CONFIG_LINK_METRICS_MANAGER_ENABLE 0
#define OPENTHREAD_CONFIG_LINK_RAW_ENABLE 0
#define OPENTHREAD_CONFIG_MULTICAST_DNS_ENABLE \
  NRF54L15_CLEAN_OPENTHREAD_MDNS_ENABLE
#define OPENTHREAD_CONFIG_MULTICAST_DNS_PUBLIC_API_ENABLE \
  NRF54L15_CLEAN_OPENTHREAD_MDNS_ENABLE
#define OPENTHREAD_CONFIG_PARENT_SEARCH_ENABLE 0
#define OPENTHREAD_CONFIG_PING_SENDER_ENABLE 0
#define OPENTHREAD_CONFIG_ECDSA_ENABLE \
  NRF54L15_CLEAN_OPENTHREAD_SRP_CLIENT_ENABLE
#define OPENTHREAD_CONFIG_SRP_CLIENT_ENABLE \
  NRF54L15_CLEAN_OPENTHREAD_SRP_CLIENT_ENABLE
#define OPENTHREAD_CONFIG_SRP_CLIENT_AUTO_START_API_ENABLE \
  NRF54L15_CLEAN_OPENTHREAD_SRP_CLIENT_ENABLE
#define OPENTHREAD_CONFIG_SRP_CLIENT_AUTO_START_DEFAULT_MODE \
  NRF54L15_CLEAN_OPENTHREAD_SRP_CLIENT_ENABLE
#define OPENTHREAD_CONFIG_SRP_CLIENT_BUFFERS_ENABLE 0
#define OPENTHREAD_CONFIG_SRP_CLIENT_SAVE_SELECTED_SERVER_ENABLE 0
#define OPENTHREAD_CONFIG_SRP_SERVER_ENABLE 0
#define OPENTHREAD_CONFIG_TMF_NETDIAG_CLIENT_ENABLE 0
#define OPENTHREAD_CONFIG_TMF_PROXY_DUA_ENABLE 0
#define OPENTHREAD_CONFIG_TMF_PROXY_MLR_ENABLE 0
#define OPENTHREAD_CONFIG_TIME_SYNC_ENABLE 0
